# Generated by Django 2.0.4 on 2019-07-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='账户')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('real_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('mail', models.EmailField(max_length=200, verbose_name='邮箱')),
                ('permission_options', models.IntegerField(default=3, verbose_name='权限分类')),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
