# Generated by Django 2.0.4 on 2019-06-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccimp_user_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPermission',
        ),
        migrations.AlterField(
            model_name='user',
            name='permission_options',
            field=models.IntegerField(default=4, verbose_name='权限分类'),
        ),
    ]
