# Generated by Django 2.0.4 on 2019-07-25 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ccimp_user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('describe', models.TextField(default='', max_length=50, verbose_name='描述')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccimp_user_app.User')),
            ],
        ),
    ]
