# Generated by Django 2.0.4 on 2019-06-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_chinese_name', models.CharField(max_length=100, verbose_name='权限中文名')),
                ('permission_english_name', models.CharField(max_length=100, verbose_name='权限英文名')),
                ('permission_options', models.IntegerField(default=4, verbose_name='权限分类')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
