# Generated by Django 2.0.4 on 2019-07-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccimp_permission_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionclass',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='permissionclass',
            name='permission_options',
            field=models.IntegerField(default=3, verbose_name='权限分类'),
        ),
    ]
