# Generated by Django 2.0.4 on 2019-07-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccimp_permission_app', '0002_auto_20190703_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionclass',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='permissionclass',
            name='update_time',
            field=models.DateTimeField(null=True),
        ),
    ]
