# Generated by Django 2.0.4 on 2019-07-03 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccimp_permission_app', '0003_auto_20190703_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionclass',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 18, 23, 46)),
        ),
    ]
