# Generated by Django 2.0.4 on 2019-07-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccimp_permission_app', '0004_auto_20190703_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionclass',
            name='create_time',
            field=models.DateTimeField(),
        ),
    ]
