# Generated by Django 2.0.4 on 2020-10-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameConfig', models.CharField(max_length=50, verbose_name='配置名称')),
                ('keyConfig', models.CharField(max_length=200, verbose_name='配置Key')),
                ('valueConfig', models.CharField(max_length=200, verbose_name='配置Value')),
                ('describeConfig', models.TextField(default='', max_length=200, verbose_name='配置描述')),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
